"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-qc&*7k241(svuqr#1iqh&py*6*12dv7^*0el5cq-cxcgh%-w+#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Le decimos que confíe en tu PC local Y en tu nueva URL de Railway
ALLOWED_HOSTS = [
    'localhost', 
    '127.0.0.1', 
    'notas-app-django-react-production.up.railway.app' # <-- ¡AGREGA ESTA LÍNEA!
    'notas-app-django-react.vercel.app'
]

# --- ¡AQUÍ ESTÁ LA CORRECCIÓN! ---
# 'CSRF_TRUSTED_ORIGINS'
# Le dice a Django que SÍ confíe en los formularios (POST)
# que vengan de su propio dominio.
CSRF_TRUSTED_ORIGINS = [
    'https://notas-app-django-react-production.up.railway.app'
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',
    'rest_framework',  # <-- ¡AGREGA ESTA LÍNEA!
    'corsheaders',
    'notas.apps.NotasConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# (Alrededor de la línea 110)

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# --- ¡AQUÍ ESTÁ LA CORRECCIÓN! ---

# 'STATIC_ROOT = ...'
# Le dice a Django: "Cuando ejecutes 'collectstatic',
# junta todos los archivos CSS/JS del Admin en una carpeta llamada 'staticfiles'".
STATIC_ROOT = BASE_DIR / 'staticfiles'

# 'STATICFILES_STORAGE = ...'
# Le dice a Whitenoise que maneje esos archivos de forma eficiente (comprimida).
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Al final del archivo
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # <-- DEBE ESTAR AQUÍ
    "https://notas-app-django-react.vercel.app"
]
